In [19]:
import pandas as pd
import numpy as np
import os 
import datetime
import matplotlib.pyplot as plt
import scipy.stats as st

In [20]:
Boston_listing_file ="c://Learn//Project1//Resources//Boston_listings.csv"
Boston_listing_df =pd.read_csv(Boston_listing_file)
Boston_listing_df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,12147973,https://www.airbnb.com/rooms/12147973,2.016090e+13,9/7/16,Sunny Bungalow in the City,"Cozy, sunny, family home. Master bedroom high...",The house has an open and cozy feel at the sam...,"Cozy, sunny, family home. Master bedroom high...",none,"Roslindale is quiet, convenient and friendly. ...",...,NaN,f,NaN,NaN,f,moderate,f,f,1,NaN
1,3075044,https://www.airbnb.com/rooms/3075044,2.016090e+13,9/7/16,Charming room in pet friendly apt,Charming and quiet room in a second floor 1910...,Small but cozy and quite room with a full size...,Charming and quiet room in a second floor 1910...,none,"The room is in Roslindale, a diverse and prima...",...,9.0,f,NaN,NaN,t,moderate,f,f,1,1.30
2,6976,https://www.airbnb.com/rooms/6976,2.016090e+13,9/7/16,Mexican Folk Art Haven in Boston,"Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...",none,The LOCATION: Roslindale is a safe and diverse...,...,10.0,f,NaN,NaN,f,moderate,t,f,1,0.47
3,1436513,https://www.airbnb.com/rooms/1436513,2.016090e+13,9/7/16,Spacious Sunny Bedroom Suite in Historic Home,Come experience the comforts of home away from...,Most places you find in Boston are small howev...,Come experience the comforts of home away from...,none,Roslindale is a lovely little neighborhood loc...,...,10.0,f,NaN,NaN,f,moderate,f,f,1,1.00
4,7651065,https://www.airbnb.com/rooms/7651065,2.016090e+13,9/7/16,Come Home to Boston,"My comfy, clean and relaxing home is one block...","Clean, attractive, private room, one block fro...","My comfy, clean and relaxing home is one block...",none,"I love the proximity to downtown, the neighbor...",...,10.0,f,NaN,NaN,f,flexible,f,f,1,2.25

In [21]:
Boston_listing_df=Boston_listing_df[["id", "name", "latitude", "longitude",  "property_type", "accommodates", "bathrooms", "bedrooms", "beds", "review_scores_rating"]]

In [18]:
month_df=df_final_boston.groupby(['month'])["price"].mean()
mean_price_by_listing_df = df_final_boston.groupby('listing_id')["price"].mean()

mean_price_by_listing_df

NameError: name 'df_final_boston' is not defined

In [16]:
Boston_listing_df.head()

,id,name,latitude,longitude,property_type,accommodates,bathrooms,bedrooms,beds,review_scores_rating
0,12147973,Sunny Bungalow in the City,42.282619,-71.133068,House,4,1.5,2.0,3.0,NaN
1,3075044,Charming room in pet friendly apt,42.286241,-71.134374,Apartment,2,1.0,1.0,1.0,94.0
2,6976,Mexican Folk Art Haven in Boston,42.292438,-71.135765,Apartment,2,1.0,1.0,1.0,98.0
3,1436513,Spacious Sunny Bedroom Suite in Historic Home,42.281106,-71.121021,House,4,1.0,1.0,2.0,100.0
4,7651065,Come Home to Boston,42.284512,-71.136258,House,2,1.5,1.0,2.0,99.0

In [17]:
Boston_listing_df["Mean Price 2016"] = 0
Boston_listing_df["Mean Price 2017"] = 0
for index, row in Boston_listing_df.head ().iterrows():
    
    try:
        Boston_listing_df.loc[index,"Mean Price 2016"] = mean_price_by_listing_df.loc[2016,row["id"]]
    except:
        Boston_listing_df.loc[index, "Mean Price 2016"] = 0
        
    try:
        Boston_listing_df.loc[index,"Mean Price 2017"] = mean_price_by_listing_df.loc[2017,row["id"]]
    except:
        Boston_listing_df.loc[index, "Mean Price 2017"] = 0
       
        
        
Boston_listing_df.head()

,id,name,latitude,longitude,property_type,accommodates,bathrooms,bedrooms,beds,review_scores_rating,Mean Price 2016,Mean Price 2017
0,12147973,Sunny Bungalow in the City,42.282619,-71.133068,House,4,1.5,2.0,3.0,NaN,0,0
1,3075044,Charming room in pet friendly apt,42.286241,-71.134374,Apartment,2,1.0,1.0,1.0,94.0,0,0
2,6976,Mexican Folk Art Haven in Boston,42.292438,-71.135765,Apartment,2,1.0,1.0,1.0,98.0,0,0
3,1436513,Spacious Sunny Bedroom Suite in Historic Home,42.281106,-71.121021,House,4,1.0,1.0,2.0,100.0,0,0
4,7651065,Come Home to Boston,42.284512,-71.136258,House,2,1.5,1.0,2.0,99.0,0,0